### ISSUE TITLE
Populated admins in groups return every user property. 

### ISSUE THREAD

**Issue by mujuni88** [mujuni88/sportsscheduler#19]
Expected: 
Everything except salt, password, created, provider, updated.

**Comment by mujuni88** [comment]
We need a solution for this that is scalable. It would be nice if I sent you all the properties I want. So you never have to always add and remove them. How does that sound @tqg5

**Comment by tqg5** [comment]
This has been on my mind for a bit. I think I can implement something that can filter the attributes returned. However there are some limitations to my approach.

PROS:
You don't have to send me attributes you want returned

CONS:
My way will be static. So if for some reason, you wanted the salt (or any other attribute that we'd normally hide) I wouldn't be able to get it to you @mujuni88
