### ISSUE TITLE
Add pagination on events and members list

### ISSUE THREAD

**Issue by mujuni88** [mujuni88/sportsscheduler#21]
If many events will be created, we would need pagination and an api to support it. @tqg5

**Comment by tqg5** [comment]
For all of the list api calls, instead of returning an array of Models, would returning an array that contained an array of Models at each index suffice? So every index of the main array would be a page. @mujuni88

**Comment by mujuni88** [comment]
I know where you are coming from but wouldn’t this approach return me all the data available?. I just want a set of data like say 5 per page. The api would look something like /to/api/users?page=0&count=10 and would return me something like 
{
	count:’Total number of data in the database’,
	data:[models, models]
} 
or
{
 	_metadata:{Count:’total number of data in the db’},
	data:[]
}
preferably _metadata because I can see us using that in other areas. 


I would like for us to stick to REST API standards to avoid future problems. @tqg5

**Comment by mujuni88** [comment]
I know where you are coming from but wouldn’t this approach return me all the data available?. I just want a set of data like say 5 per page. The api would look something like /to/api/users?page=0&count=10 and would return me something like 
{
	count:’Total number of data in the database’,
	data:[models, models]
} 
or
{
 	_metadata:{Count:’total number of data in the db’},
	data:[]
}
preferably _metadata because I can see us using that in other areas. 


I would like for us to stick to REST API standards to avoid future problems.

**Comment by mujuni88** [comment]
Hey @tqg5, here is the library i'm using https://github.com/michaelbromley/angularUtils/tree/master/src/directives/pagination#working-with-asynchronous-data

They show a way to implement the api for the server as well.

**Comment by tqg5** [comment]
I'm not really sure how to paginate members. I can paginate events easy enough since you're reading from a separate api to get the events. But since you're just getting a group and reading from the members attribute I'm not sure how that's supposed to be paginated @mujuni88

**Comment by mujuni88** [comment]
@tqg5 for members we will do the pagination that i'm currently doing. I don't think we need to complicate it.
