### ISSUE TITLE
Fix the server validation methods for event fields

### ISSUE THREAD

**Issue by mujuni88** [mujuni88/sportsscheduler#32]
Hey @tqg5, not sure if you already did this but just wanted to remind you.

**Comment by tqg5** [comment]
Which validation methods? @mujuni88

**Comment by mujuni88** [comment]
The things we discussed last time like location.name having a character limit etc.

**Comment by tqg5** [comment]
Why not just leave them as they are for testing? We don't really know the exact regex will want to test against yet do we? @mujuni88
