### ISSUE TITLE
Getting error while trying to vote on an event

### ISSUE THREAD

**Issue by mujuni88** [mujuni88/sportsscheduler#36]
Hey @tqg5, when I try to vote and update, I get "User does not exist". Do you know what's happening here

**Comment by tqg5** [comment]
What's the request body? @mujuni88

**Comment by mujuni88** [comment]
{"_id":"5536778776e23e0000fa1c35","minimumVotes":0,"date":"2015-04-21T16:14:50.653Z","time":"2015-04-21T19:14:50.653Z","message":"Test","name":"Wfgfsgfg","group":"553668fae5fde000009b7b45","__v":0,"votes":{"no":[],"yes":[{"_id":"5509f6a1b980bfd4fde705ee","displayName":"Teresia Buza","provider":"local","firstName":"Teresia","lastName":"Buza","username":"tbuza","__v":0,"created":"2015-03-18T22:05:21.892Z","updated":"2015-03-18T22:05:21.892Z","roles":["user"],"addedBy":[],"joinedGroups":[],"createdGroups":[],"plainTextPassword":"","phoneNumber":6626174248,"carrier":"@blueskyfrog.com","email":"joe_buza@me.com"}]},"voteEnabled":true,"location":{"address":"sgfgsfgfdg","lng":-1,"lat":-1,"name":"fgsfgsg"},"created":"2015-04-21T16:15:03.690Z"}
