### ISSUE TITLE
Display name returns undefined undefined 

### ISSUE THREAD

**Issue by mujuni88** [mujuni88/sportsscheduler#52]
__v: 0
_id: "5550d8573a87240000873fb8"
addedBy: []
carrier: "@sms.alltelwireless.com"
created: "2015-05-11T16:27:03.342Z"
createdGroups: []
displayName: "undefined undefined"
email: "jbuza@gmail.com"

**Comment by mujuni88** [comment]
Go to https://sportsscheduler.herokuapp.com/#!/ and login using cbuza and our usual password

**Comment by tqg5** [comment]
Haven't been able to reproduce this. @mujuni88

**Comment by mujuni88** [comment]
1. Login to https://sportsscheduler.herokuapp.com/#!/
2. Create a group 
3. Search for a group to join by typing "group"
4. Join the group
5. Click List group on the dropdown button at the menu bar
6. Click on the joined group
7. You should see, undefined undefined
