### ISSUE TITLE
What happens when an event is deleted or cancelled

### ISSUE THREAD

**Issue by mujuni88** [mujuni88/sportsscheduler#77]
What happens when a user wants to cancel or delete an event say due to unexpected weather?
1. We should provide them with a cancel button
2. When a user deletes/cancel, members should receive a message or text

**Comment by tqg5** [comment]
When the event DELETE is called I'll implement sending an email and/or text to all of the members and admins @mujuni88

**Comment by tqg5** [comment]
Realized this ticket had 2 parts in it (the cancel button) so will re-open until that's done @mujuni88
